# Generated by Django 2.1.5 on 2019-03-29 03:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayTime', models.DateTimeField(default=None, null=True)),
                ('category', models.TextField()),
                ('subCategory', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('title', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('name', models.TextField()),
                ('cellPhone', models.TextField()),
            ],
        ),
    ]
