# Generated by Django 2.1.5 on 2019-03-29 04:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cellPhone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
