# Generated by Django 2.1.5 on 2019-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190328_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='brand',
            field=models.TextField(null=True),
        ),
    ]
