# Generated by Django 2.1.5 on 2019-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_ad_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
