# Generated by Django 2.1.5 on 2019-04-03 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_ad_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayTime', models.DateTimeField(default=None, null=True)),
                ('category', models.TextField()),
                ('subCategory', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, null=True)),
                ('title', models.TextField()),
                ('year', models.IntegerField(null=True)),
                ('brand', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('cellPhone', models.TextField(null=True)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
