# Generated by Django 2.1.5 on 2019-04-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_recentads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='favorited',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='favorited',
            field=models.IntegerField(null=True),
        ),
    ]
