# Generated by Django 2.1.5 on 2019-04-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190402_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='favorited',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recentads',
            name='favorited',
            field=models.TextField(null=True),
        ),
    ]
