# Generated by Django 2.1.5 on 2019-04-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190402_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
