# Generated by Django 2.1.5 on 2019-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190403_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='kbb_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='kbb_value',
            field=models.TextField(null=True),
        ),
    ]
