# Generated by Django 2.1.5 on 2019-04-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20190404_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='make',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='make',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='model',
            field=models.TextField(null=True),
        ),
    ]
