# Generated by Django 2.1.5 on 2019-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20190404_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='difference',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='difference',
            field=models.TextField(null=True),
        ),
    ]
