# Generated by Django 2.1.5 on 2019-04-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190404_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ksl_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentads',
            name='ksl_id',
            field=models.TextField(null=True),
        ),
    ]
