# Generated by Django 2.1.5 on 2019-04-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20190404_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default=None, null=True)),
                ('charge_id', models.TextField(default=None, null=True)),
            ],
        ),
    ]
