# Generated by Django 2.1.5 on 2019-06-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_pros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(default=None, null=True)),
                ('plan_id', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pros',
            name='stripe_customer_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
