# Generated by Django 2.1.5 on 2019-06-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_ad_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentads',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
