# Generated by Django 2.1.5 on 2019-06-14 03:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_recentads_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='recentads',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, null=True),
        ),
    ]
